#!/usr/bin/env bash
set -eu
vim=

while getopts "v" o; do
    case "${o}" in
        v)
            vim=yes;;
        *)
            echo "Invalid option"; exit 1;
            ;;
    esac
done
shift $((OPTIND-1))


RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${1:-""}"
O=$(FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true" \
  --ansi --phony --query "$INITIAL_QUERY")

[[ -z $O ]] && exit

echo ${O/:*}
[[ -n ${vim} ]] && exec vim ${O/:*}
