#!/usr/bin/env bash
set -eu
vim= emacsclient= line= column= O= editor=

while getopts "vme" o; do
    case "${o}" in
        v)
            vim=yes;;
        m)
            emacsclient=yes;;
        e)
            editor=yes;;
        *)
            echo "Invalid option"; exit 1;
            ;;
    esac
done
shift $((OPTIND-1))


RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${1:-""}"
O=$(FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true" \
  --ansi --phony --query "$INITIAL_QUERY")

[[ -z $O ]] && exit

echo ${O/:*}

[[ $O =~ (.*):([0-9]*):([0-9]*): ]] && {
    filename=${BASH_REMATCH[1]}
    line=${BASH_REMATCH[2]}
    column=${BASH_REMATCH[3]}
}

[[ -n ${vim} ]] && vim +${line} -c "execute \"normal /${INITIAL_QUERY}\n\"" ${O/:*}
[[ -n ${emacsclient} ]] && emacsclient +${line}:${column} -n  ${O/:*}
[[ -n ${editor} ]] && ${EDITOR} +${line}:${column} ${O/:*}
