#!/usr/bin/env bash
set -eu
loop=yes vim=yes emacsclient= line= column= O= editor= all= editall=

TMP=$(mktemp /tmp/.mm.XXXXXX)
clean() { rm -f ${TMP}; }
trap clean EXIT

while getopts "anmet:" o; do
    case "${o}" in
        t)
            TMP=${OPTARG};;
        a)
            loop=;editall=yes;;
        n)
            vim=;;
        m)
            emacsclient=yes;;
        e)
            editor=yes;;
        *)
            echo "Invalid option"; exit 1;
            ;;
    esac
done
shift $((OPTIND-1))

RG_PREFIX="rg --column --line-number --no-heading --color=always --case-sensitive "
INITIAL_QUERY="${1:-""}"
echo ${INITIAL_QUERY} > ${TMP}
RES=$(FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true;echo {q} > ${TMP}" \
  --ansi --phony --query "$INITIAL_QUERY")

[[ -z $RES ]] && exit

QUERY=$(cat ${TMP})

function edit() {
    local res="${1}"
    local query="${2}"
    [[ ${res} =~ (.*):([0-9]*):([0-9]*) ]] && {
        filename=${BASH_REMATCH[1]}
        line=${BASH_REMATCH[2]}
        column=${BASH_REMATCH[3]}
    }
    echo ${filename}

    set +e
    [[ -n ${vim} ]] && vim +${line} -c "normal ${column}|\n\"" ${filename}
    [[ -n ${emacsclient} ]] && emacsclient +${line}:${column} ${filename}
    [[ -n ${editor} ]] && ${EDITOR} +${line}:${column} ${filename}
    set -e
}

if [[ -n ${editall} ]];then
    match=($(${RG_PREFIX} --color=never  ${QUERY}|grep -Eo '^([^:]*?):([0-9]*):([0-9]*)'))
else
    match=($(echo ${RES}|grep -Eo '^([^:]*?):([0-9]*):([0-9]*)'))
fi

if [[ -n ${loop} ]];then
    edit "${match[0]}" "$QUERY"
    while True;do
        ${0} -t ${TMP} ${QUERY}
        QUERY=$(cat ${TMP})
        read
    done
fi

for r in ${match[@]};do
    edit "$r" "$QUERY"
    [[ -z ${editall} ]] && break
done
