#!/usr/bin/env bash
titleonly=

while getopts "cb" o; do
    case "${o}" in
        c)
            commitmessage=t
            ;;
        b)
            createbranch=t
            ;;
        *)
            echo "Invalid option"; exit 1;
            ;;
    esac
done
shift $((OPTIND-1))


ARGS=${@}
[[ -n ${@} ]] && ARGS="-q $@"

#title=$(osascript -e 'tell application "Firefox" to return name of windows as text')
title=$(hub issue|fzf -1 ${ARGS} --header "Choose a GitHUB Issue" --tac --preview="hub issue show \`echo {}|sed 's/#\([0-9]*\).*/\1/'\`")
number=$(echo $title|sed 's/[ ]*#\([0-9]*\).*/\1/')

if [[ ${commitmessage} ]];then
    echo $title|sed -r 's/[ ]*#[0-9]+[ ]*//;'
    echo
    echo "Closes #$number"
    exit
fi

prefix=$(echo "$title"|sed -r 's,kind/\w+,,;s/help wanted//;s/[ ]*#(.*)/\L\1/;s/ [ ]*/ /g;s/[ ]*$//;s/^[ ]*//;s/ /-/g;s,\(/\`||:|;|"|\|\),,g')
prefix=$(echo "$prefix"|awk -v len=25 '{ if (length($0) > len) print substr($0, 1, len-3); else print; }')
[[ $prefix == *- ]] && prefix=$(echo ${prefix}| sed 's/-$//')


if [[ -z ${title} || -z ${number} ]];then
    echo "Can't get title or number"
    exit
fi

[[ -n ${createbranch} ]] && { git checkout -b issue-${prefix} ; exit 0 ;}
echo issue-${prefix}
