#!/usr/bin/env bash
read -e -p "Branch name: " BRANCH_NAME
git stash &&
    git checkout master &&
    git fetch origin &&
    git rebase origin/master &&
    git checkout -b ${BRANCH_NAME} &&
    git stash pop
