#!/usr/bin/env bash
#from https://gist.github.com/junegunn/f4fca918e937e6bf5bad
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --height=30% --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-e:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'emacsclient %|less;sleep 10') << 'FZF-EOF'
                {}
FZF-EOF" \
      --bind "ctrl-o:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git browse %') << 'FZF-EOF'
                {}
FZF-EOF" \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}
fshow
