#!/usr/bin/env bash
set -eu

farg=""
klogopt=""
kgetpodopt=""
onlypod=

[[ $(basename $0) == GP ]] && onlypod=yes

cat <<EOF
ocla substring

This will let you choose a pod with fzf and show logs

-o don't show logs, only output pod
-r filter to only running pods
-f show logs and follow them
-1 choose the first one found in substring

EOF

while getopts "rf1o" o; do
    case "${o}" in
        o)
            onlypod=yes;;
        1)
            farg="${farg} -1";;
        r)
            kgetpodopt="${kgetpodopt} --field-selector status.phase=Running"
            ;;
        f)
            klogopt="${klogopt} -f"
            kgetpodopt="--field-selector status.phase=Running"
            ;;
        *)
            echo "Invalid option"; exit 1;

            ;;
    esac
done
shift $((OPTIND-1))

ARG1=${1:-}
if [[ -n ${ARG1} ]];then
    farg="${farg} -q ${ARG1}"
    shift
fi

POD=$(kubectl get pod --no-headers ${kgetpodopt} --sort-by=.metadata.creationTimestamp|fzf --tac --layout=reverse ${farg} --height=10%|awk '{print $1}')
if [[ -z ${POD} ]];then
    exit
fi

if [[ -n ${onlypod} ]];then
	echo $POD
else
	kubectl logs --max-log-requests=20 --all-containers ${POD} ${klogopt}
fi
