#!/usr/bin/env bash
set -e

# default upstream branch called upstream may be origin for you
upstream=upstream

PR=${1}

[[ ${PR} != *tektoncd/catalog* ]] && {
    echo "i need the first argument to be a tekton/catalog PR"
    exit
}

cd "$GOPATH/src/github.com/tektoncd/catalog"

hub checkout "${PR}"

changed_task_version=$(git diff-tree --no-commit-id --name-only -r $(git rev-parse --abbrev-ref HEAD)|grep '^task/'| \
                           sed 's,\([^/]*/[^/]*/[^/]*\).*,\1,'|sort -u)

if [[ -z ${changed_task_version} ]];then
    echo "Not a commit with a change in task"
    exit 0
fi

check_if_task_version_on_main=$(git ls-tree -r ${upstream}/main --name-only ${changed_task_version} || true)
if [[ -n ${check_if_task_version_on_main} ]];then
    echo "Not a new version, since '${changed_task_version}' is already in main"
    exit 0
fi

task_name=$(basename $(dirname ${changed_task_version}))
task_version=$(basename ${changed_task_version})

previous_task_version=$(ls task/${task_name}|sort -ur|grep '^[0-9]*\.[0-9]*'|grep -v ${task_version} | head -1)

difffilename=/tmp/catalog-review-${task_name}-${task_version}.diff

diff -urN task/${task_name}/${previous_task_version} task/${task_name}/${task_version} | \
    tee ${difffilename}

type -p pastegg >/dev/null 2>/dev/null && \
    pastegg -f ${difffilename} | tee ${difffilename/.diff/.pasteurl}
